export const IMAGES_LOAD = 'IMAGES_LOAD';
export const IMAGES_LOAD_SUCCESS = 'IMAGES_LOAD_SUCCESS';
export const IMAGES_LOAD_FAIL = 'IMAGES_LOAD_FAIL';
export const STATS_LOAD_FAIL = 'STATS_LOAD_FAIL';
export const STATS_LOAD_SUCESS = 'STATS_LOAD_SUCESS';
export const STATS_LOAD = 'STATS_LOAD';
